### ISSUE TITLE
The system get stuck after add-apt-repository ppa and install kodi

### ISSUE THREAD

**Issue by xiayang0521** [amazingfate/armbian-rock5b-images#1]
After follow these commands by using the latest armbian jammy desktop image

add-apt-repository ppa:liujianfeng1994/panfork-mesa
add-apt-repository ppa:liujianfeng1994/rockchip-multimedia
apt update
apt dist-upgrade
apt install kodi

I find the system may get stuck when using the desktop and the system will not get stuck when just using the CLI through ssh.

**Comment by amazingfate** [comment]
> After follow these commands by using the latest armbian jammy desktop image
> 
> add-apt-repository ppa:liujianfeng1994/panfork-mesa add-apt-repository ppa:liujianfeng1994/rockchip-multimedia apt update apt dist-upgrade apt install kodi
> 
> I find the system may get stuck when using the desktop and the system will not get stuck when just using the CLI through ssh.

What's the meaning of system, the dekstop environment or the entire linux system?

**Comment by xiayang0521** [comment]
the entire linux system

**Comment by xiayang0521** [comment]
> > After follow these commands by using the latest armbian jammy desktop image
> > add-apt-repository ppa:liujianfeng1994/panfork-mesa add-apt-repository ppa:liujianfeng1994/rockchip-multimedia apt update apt dist-upgrade apt install kodi
> > I find the system may get stuck when using the desktop and the system will not get stuck when just using the CLI through ssh.
> 
> What's the meaning of system, the dekstop environment or the entire linux system?

the entire linux system

**Comment by amazingfate** [comment]
> > > After follow these commands by using the latest armbian jammy desktop image
> > > add-apt-repository ppa:liujianfeng1994/panfork-mesa add-apt-repository ppa:liujianfeng1994/rockchip-multimedia apt update apt dist-upgrade apt install kodi
> > > I find the system may get stuck when using the desktop and the system will not get stuck when just using the CLI through ssh.
> > 
> > 
> > What's the meaning of system, the dekstop environment or the entire linux system?
> 
> the entire linux system

You can connect to a serial console and see the kernel log when system gets stuck.

**Comment by chapas** [comment]
Same issue here, how to connect to the serial console?

**Comment by amazingfate** [comment]
Seem to be a power issue.
