### ISSUE TITLE
How did you build the image including Firmware patches?

### ISSUE THREAD

**Issue by heresiarch** [amazingfate/armbian-rock5b-images#3]
I would like to build a image for Rock4B. Could you please describe what modifications you did for mesa and firmware in your armbian build please? Or could you build a version for Rock 4B please?
I'm following the discussion here: https://forum.armbian.com/topic/24802-kodi-for-rk35xx-510-legacy-kernel/

**Comment by amazingfate** [comment]
What firmware do you want? Rock4B is a different hardware.
